M48
; DRILL file {KiCad (6.0.2)} date Wed 09 Mar 2022 02:23:40 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-09T14:23:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X182.9Y-83.11
X182.9Y-88.89
T2
X150.56Y-80.8
X155.64Y-79.784
X155.64Y-81.816
T0
M30
